export const saleOrderInitialValues = {
    searchOrderCode: "",

    customerId: "",
    customerID: "",
    
    settlementDate: "",
    exitType: "1",
    orderSendTypeId: "1",
    paymentTypeId: "2",
    // isTemporary: "0",
    isTemporary: false,
    invoiceTypeId: "",
    customerOfficialName: "",
    customerOfficialCompanyId: "",
    // Order
    rowId: "",
    id: "",
    warehouseId: "",
    warehouseTypeId: "",
    proximateAmount: "",
    numberInPackage: "",
    productDesc: "",
    price: "",
    cargoSendDate: "",
    purchasePrice: "",
    purchaseInvoiceTypeId: "",
    purchaserCustomerId: "",
    purchaseSettlementDate: "",
    sellerCompanyRow: "",
    // not Main
    productName: "",
    warehouseName: "",
    proximateSubUnit: "",
    mainUnit: "",
    subUnit: "",
    productSubUnitId: "",
    productBrandId: "",
    productBrandName: "",
    purchaserCustomerName: ""
};
